behavior:
  ros__parameters:
    frequency: 10.0 # {double} [Hz]
    plan_frequency: 2.0 # {double} [Hz]

controller:
  ros__parameters:
    frequency: 20.0 # {double} [Hz]
    lookahead_distance: 0.1 # {double} [m]
    lookahead_lin_vel: 0.2 # {double} [m/s]
    stop_thres: 0.1 # {double} [m]
    max_lin_vel: 4.0 # {double} [m/s]
    safe_lin_vel: 1.5 # {double} [m/s]
    max_ang_vel: 2.0 # {double} [rad/s]
    turn_dist: 0.4 # {double} [m]
    K_p: 6.0 # {float} []
    K_i: 0.1 # {float} []
    K_d: 0.05 # {float} []
    startup_threshold: 0.1 # {float} [rad]
    steepness_factor: 3.0 # {float} []

planner:
  ros__parameters:
    max_access_cost: 90 # {int} []
    max_skipping_cost: 10 # {int} []
    max_skipping_dist: 5.0 # {double} [m]
